#pragma once
// GENERATED by tools/gerber_to_panel.py from res-src/AI018-gerbers — do not edit by hand.
// Hole centres in millimetres, matching res/AI018-black.svg.
namespace ai018layout {
struct Pos { float x, y; };
constexpr Pos IN_L1 = {6.842f, 15.813f};  // hole Ø6.75 mm
constexpr Pos IN_R1 = {6.842f, 26.546f};  // hole Ø6.75 mm
constexpr Pos IN_L2 = {6.842f, 37.064f};  // hole Ø6.75 mm
constexpr Pos IN_R2 = {6.842f, 47.797f};  // hole Ø6.75 mm
constexpr Pos IN_L3 = {6.842f, 58.314f};  // hole Ø6.75 mm
constexpr Pos IN_R3 = {6.842f, 69.048f};  // hole Ø6.75 mm
constexpr Pos IN_L4 = {6.842f, 79.565f};  // hole Ø6.75 mm
constexpr Pos IN_R4 = {6.842f, 90.299f};  // hole Ø6.75 mm
constexpr Pos KNOB_1A = {23.917f, 21.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_1B = {42.747f, 21.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_1C = {61.577f, 21.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_1D = {80.417f, 21.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_2A = {23.917f, 42.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_2B = {42.747f, 42.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_2C = {61.577f, 42.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_2D = {80.417f, 42.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_3A = {23.917f, 63.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_3B = {42.747f, 63.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_3C = {61.577f, 63.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_3D = {80.417f, 63.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_4A = {23.917f, 84.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_4B = {42.747f, 84.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_4C = {61.577f, 84.585f};  // hole Ø7.50 mm
constexpr Pos KNOB_4D = {80.417f, 84.585f};  // hole Ø7.50 mm
constexpr Pos OUT_LA = {23.917f, 102.517f};  // hole Ø6.75 mm
constexpr Pos OUT_RA = {23.917f, 113.250f};  // hole Ø6.75 mm
constexpr Pos OUT_LB = {42.747f, 102.517f};  // hole Ø6.75 mm
constexpr Pos OUT_RB = {42.747f, 113.250f};  // hole Ø6.75 mm
constexpr Pos OUT_LC = {61.577f, 102.517f};  // hole Ø6.75 mm
constexpr Pos OUT_RC = {61.577f, 113.250f};  // hole Ø6.75 mm
constexpr Pos OUT_LD = {80.417f, 102.517f};  // hole Ø6.75 mm
constexpr Pos OUT_RD = {80.417f, 113.250f};  // hole Ø6.75 mm
constexpr Pos SCREW_TL = {7.57f, 3.0f};
constexpr Pos SCREW_TR = {83.77f, 3.0f};
constexpr Pos SCREW_BL = {7.57f, 125.5f};
constexpr Pos SCREW_BR = {83.77f, 125.5f};
constexpr float PANEL_WIDTH = 91.44f;
}  // namespace ai018layout
