#pragma once
// GENERATED by tools/gerber_to_panel.py from res-src/AI250-gerbers — do not edit by hand.
// Hole centres in millimetres, matching res/AI250-black.svg.
namespace ai250layout {
struct Pos { float x, y; };
constexpr Pos KNOB_ARG = {17.860f, 22.820f};  // hole Ø7.54 mm
constexpr Pos KNOB_FUNC = {53.260f, 22.820f};  // hole Ø7.54 mm
constexpr Pos KNOB_IN1VOL = {10.610f, 46.134f};  // hole Ø7.54 mm
constexpr Pos KNOB_WAVE = {35.560f, 46.134f};  // hole Ø7.54 mm
constexpr Pos KNOB_DIST = {60.510f, 46.134f};  // hole Ø7.54 mm
constexpr Pos SWITCH_IN2OSC = {23.560f, 57.789f};  // hole Ø7.14 mm
constexpr Pos SWITCH_SPEED = {47.560f, 57.789f};  // hole Ø7.14 mm
constexpr Pos KNOB_CENTER = {10.610f, 69.444f};  // hole Ø7.54 mm
constexpr Pos KNOB_MIX = {60.510f, 69.444f};  // hole Ø7.54 mm
constexpr Pos IN_VOCT = {23.560f, 78.681f};  // hole Ø6.75 mm
constexpr Pos IN_WAVE_CV = {35.560f, 78.681f};  // hole Ø6.75 mm
constexpr Pos IN_MIX_CV = {47.560f, 78.681f};  // hole Ø6.75 mm
constexpr Pos LIGHT_GATE1 = {49.147f, 88.936f};  // hole Ø3.17 mm
constexpr Pos LIGHT_GATE2 = {61.147f, 88.936f};  // hole Ø3.17 mm
constexpr Pos IN_ARG_CV = {11.560f, 95.681f};  // hole Ø6.75 mm
constexpr Pos IN_FUNC_CV = {23.560f, 95.681f};  // hole Ø6.75 mm
constexpr Pos IN_DIST_CV = {35.560f, 95.681f};  // hole Ø6.75 mm
constexpr Pos OUT_GATE1 = {47.560f, 95.681f};  // hole Ø6.75 mm
constexpr Pos OUT_GATE2 = {59.560f, 95.681f};  // hole Ø6.75 mm
constexpr Pos IN_IN1 = {11.560f, 112.681f};  // hole Ø6.75 mm
constexpr Pos SWITCH_SWAP = {23.560f, 112.681f};  // hole Ø7.14 mm
constexpr Pos IN_IN2 = {35.560f, 112.681f};  // hole Ø6.75 mm
constexpr Pos OUT_OSC = {47.560f, 112.681f};  // hole Ø6.75 mm
constexpr Pos OUT_OUT = {59.560f, 112.681f};  // hole Ø6.75 mm
constexpr Pos SCREW_TL = {7.66f, 3.0f};
constexpr Pos SCREW_TR = {63.54f, 3.0f};
constexpr Pos SCREW_BL = {7.66f, 125.5f};
constexpr Pos SCREW_BR = {63.54f, 125.5f};
constexpr float PANEL_WIDTH = 71.12f;
}  // namespace ai250layout
